---
title: "storytelling_gastos_entes"
author: "Fernando Almeida Barbalho"
date: "2026-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(colorspace)
library(deflateBR)
library(ggbeeswarm)


#Matéria sobre gastos com segurança pública pelos municípios
#https://cnm.org.br/comunicacao/noticias/gastos-dos-municipios-com-seguranca-cresceram-66-na-ultima-decada-revela-estudo-da-cnm

#gráfico usando dados da matéria:

dados_2016_2025<- tibble(exercicio = 2016:2025, valor=c(7.47, 7.5, 7.83, 8.45, 8.54,  8.06, 9.7, 10.95, 12.6, 12.4))

#Esse dado abaixo foi gerado a partir de tratamento do dados disponibilizado no tesouro transparente. Vide projeto COFOG_VPR
despesa_governo_tidy <- read_csv("despesa_governo_tidy.csv")

#dados de estados gerados a partir de funções do pacote rsifonfi. A geração foi feita no projeto fontesdedados

gastos_estados_2021 <- readRDS("~/Github/seguranca_publica/gastos_estados_2021.rds")

gastos_estados_2025 <- readRDS("~/Github/seguranca_publica/gastos_estados_2025.rds")

finbra_2021 <- 
  read_delim("finbra_2021.csv", 
             delim = ";", escape_double = FALSE, locale = locale(decimal_mark = ",", 
                                                                 grouping_mark = ".", encoding = "latin1"), 
             trim_ws = TRUE, skip = 3) %>%
  janitor::clean_names()



finbra_2025 <- 
  read_delim("finbra_2025.csv", 
             delim = ";", escape_double = FALSE, locale = locale(decimal_mark = ",", 
                                                                 grouping_mark = ".", encoding = "latin1"), 
             trim_ws = TRUE, skip = 3)%>%
  janitor::clean_names()

num_indice_dez_2021 <- 6120.04
num_indice_dez_2025 <- 7403.29

theme_vpr<- function(paleta_cores){
  
  theme_light() +
    theme(
      panel.background = element_rect(fill= paleta_cores$cor_fundo_painel),
      panel.grid = element_blank(),
      legend.position = "right",
      legend.background = element_rect(fill= paleta_cores$cor_fundo, color = paleta_cores$cor_fundo),
      legend.title = element_blank(),
      legend.text = element_text(size = 8),
      plot.background = element_rect(fill =paleta_cores$cor_fundo ),
      plot.title = element_text(size = 14, face = "bold"),
      plot.subtitle = element_text(size = 12, face = "italic"),
      text = element_text( colour = paleta_cores$cor_texto),
      strip.background = element_rect(fill = paleta_cores$cor_fundo  ),
      strip.text = element_text(size= 8, face ="bold", color = paleta_cores$cor_texto)
    )  
  
  
}


paleta_cores<- list(  cor_fundo= "#D0D0D0", # "#E0E0E0", # # "#F8F8F8",
                      
                      cor_fundo_painel = "#F5F5F5",
                      
                      cor_fundo_estados = "#696969",
                      
                      cor_fundo_mapa_pontos = "#2B2B2B", #"#505050"
                      
                      cor_texto = "#324e5a"
)

```


```{r fig.dpi= 300}

dados_2016_2025  %>%
  ggplot(aes(x= exercicio, y= valor)) +
  geom_col(aes(fill = valor), show.legend = FALSE) +
  geom_smooth() +
  geom_text(aes(label = scales::number(valor, accuracy = 0.1, decimal.mark = ",")),
            vjust =-1,
            color =paleta_cores$cor_texto,
            fontface = "bold") +
  scale_fill_continuous_sequential(palette = "Heat 2") +
  scale_x_continuous(breaks = 2016:2025) +
  theme_vpr(paleta_cores = paleta_cores) +
  theme(
    axis.text.y= element_blank(),
    axis.title = element_blank()
  ) +
  labs(
    title = "Gastos de municípios em segurança pública",
    subtitle = "Valores aumentam substancialmente a partir de 2022. (valores em R$ bi)",
    caption = "Fonte: Confederação Nacional dos Municípios. Elaboração: VPR/DIESO"
  )

```

```{r fig.dpi= 300}
# 
# dados_base_seguranca<-
#   despesa_governo_tidy %>%
#   filter(tipo_despesa == "Ordem pública e segurança")
# 
# dados_total_seguranca<-
#   dados_base_seguranca %>%
#   filter(!esfera_governo %in% c("Governo Geral", "Coluna de Consolidação") ) %>%
#   summarise(total_seguranca_ano = sum(valor_despesa),
#             .by = ano)
# 
# dados_grafico_seguranca<-
#   dados_base_seguranca %>%
#   filter(!esfera_governo %in% c("Governo Geral", "Coluna de Consolidação") ) %>%
#   inner_join(dados_total_seguranca) %>%
#   mutate(participacao = valor_despesa/total_seguranca_ano) %>%
#   mutate(esfera_governo = factor(esfera_governo, levels = c("Governos Municipais", "Governos Estaduais","Governo Central"  )))
# 
# 
# dados_grafico_seguranca %>%
#   ggplot(aes(x=ano, y=participacao) ) +
#   geom_col(aes(fill= esfera_governo)) +
#   geom_text(aes(label = scales::percent(participacao, accuracy = 0.1, decimal.mark = ",")),
#             size = 3,
#             position =  "stack",
#             vjust= 1,
#             color= "white",
#             fontface = "bold") +
#   scale_x_continuous(breaks = 2010:2024) +
#   theme_vpr(paleta_cores = paleta_cores) +
#   theme(
#     legend.position = "bottom",
#     axis.title = element_blank(),
#     axis.text.y = element_blank()
#   ) +
#   labs(
#     title = "Participação das esferas de governo na despesa com segurança pública",
#     subtitle = "Valores relativos ao gasto do governo geral sem ajustes de consolidação",
#     caption = "Fonte: STN/COFOG. Elaboração: VPR/DIESO"
#   )

```

```{r fig.dpi= 300}

#Dados da STN (COFOG) indicam que em 2024 a segurança pública representou 17% dos gastos dos estados, 2% dos gastos da União e 1% dos gastos dos municípios



dados_grafico_comparacao_estados<-
  gastos_estados_2025 %>%
  filter(coluna == "Despesas Liquidadas") %>%
  mutate(valor_2025 = valor) %>%
  select(uf, valor_2025) %>%
  inner_join(
    gastos_estados_2021 %>%
      filter(coluna == "Despesas Liquidadas") %>%
      mutate(valor_2021 = valor) %>%
      mutate(data_nominal = as.Date(paste0(exercicio+1,"-01-01")) ) %>%
      mutate(valor_2021_corrigido_2025 = ipca(valor, data_nominal, "12/2025") ) %>%
      select(uf, valor_2021, valor_2021_corrigido_2025)    
  ) %>%
  mutate(variacao_despesa_seg_publica = (valor_2025/valor_2021_corrigido_2025)-1) %>%
  mutate(uf = reorder(uf, variacao_despesa_seg_publica))

media_variacao_anos<- mean(dados_grafico_comparacao_estados$variacao_despesa_seg_publica)
variacao_maxima<- max(dados_grafico_comparacao_estados$variacao_despesa_seg_publica)


dados_grafico_comparacao_estados %>%
  ggplot(aes(x= variacao_despesa_seg_publica, y= uf)) +
  geom_col(aes(fill= variacao_despesa_seg_publica), show.legend = FALSE) +
  geom_vline(xintercept = media_variacao_anos, linetype = "dashed", size = 1) +
  geom_text(aes(label = scales::percent(variacao_despesa_seg_publica, accuracy = 1.0, decimal.mark = ",")),
            hjust = -0.05,
            color = paleta_cores$cor_texto,
            size =3) +
  geom_curve( data = tibble(variacao_despesa_seg_publica = media_variacao_anos, uf= "SC"),
              aes( xend = 0.56, yend = "SP"),
              curvature = -0.25, ncp = 50,
              arrow = arrow(length = unit(3, "mm"), type = "closed"),
              color = paleta_cores$cor_texto
  )   +
  
  geom_text(data= tibble(variacao_despesa_seg_publica = 0.56, uf= "SP"), 
            aes(label = "Variação média das despesas"),
            vjust = 1,
            color = paleta_cores$cor_texto) +
  scale_fill_continuous_sequential(palette= "Heat 2") +
  scale_x_continuous(expand = expansion(mult = c(0.01, 0.06)), breaks = media_variacao_anos, labels = scales::percent_format(accuracy = 1.0, decimal.mark = ",")) +
  theme_vpr(paleta_cores = paleta_cores) +
  theme(
    axis.title = element_blank(),
    
  ) +
  labs(
    title = "Variação de desespas dos estados com Segurança Pública",
    subtitle = "Comparação entre valores de 2025 e 2021 corrigidos pelo IPCA",
    caption = "Fonte: STN/SICONFI. Elaboração: VPR/DIESO"
  )

```

```{r fig.dpi= 300}

# participacao_seg_publica<-
# finbra_2021 %>%
#   filter(conta %in% c("06 - Segurança Pública", "Despesas Exceto Intraorçamentárias" ),
#          coluna == "Despesas Liquidadas")%>%
#   summarise(total = sum(valor),
#             .by = conta) %>%
#   pivot_wider(names_from = conta,
#               values_from = total) %>%
#   mutate(part_seg_pub = `06 - Segurança Pública`/`Despesas Exceto Intraorçamentárias`)
# 
# 
# part_min<- (participacao_seg_publica$part_seg_pub)*0.10
# 
# 
# participacao_municipios<-
#   finbra_2021 %>%
#   filter(conta %in% c("06 - Segurança Pública", "Despesas Exceto Intraorçamentárias" ),
#          coluna == "Despesas Liquidadas")%>%
#   summarise(total = sum(valor),
#             .by = c(instituicao,conta)) %>%
#   pivot_wider(names_from = conta,
#               values_from = total) %>%
#   filter(!is.na(`06 - Segurança Pública`)) %>%
#   mutate(part_seg_pub = `06 - Segurança Pública`/`Despesas Exceto Intraorçamentárias`)
# 
# 
# quantile(participacao_municipios$part_seg_pub)*100
# quantile(participacao_municipios$part_seg_pub, probs = 0.1)*100
# 
# municipios_excluidos<-
# participacao_municipios  %>%
#   filter(`06 - Segurança Pública` <100000) %>%
#   filter(part_seg_pub <part_min ) 
# 
# 
# 
# dados_grafico_variacao_municipios<-
# 
#   finbra_2021 %>%
#   filter(conta == "06 - Segurança Pública",
#          coluna == "Despesas Liquidadas") %>%
#   mutate(valor_2021 = valor) %>%
#   select(instituicao, cod_ibge, valor_2021) %>%
#   inner_join(
#     finbra_2025 %>%
#       filter(conta == "06 - Segurança Pública",
#              coluna == "Despesas Liquidadas") %>%
#       mutate(valor_2025 = valor)%>%
#       select(instituicao,cod_ibge, valor_2025,populacao)
#   ) %>%
#   mutate(valor_2021_corrigido_2025 = valor_2021 * ((num_indice_dez_2025/num_indice_dez_2021)),
#          variacao_perc = ((valor_2025/valor_2021_corrigido_2025)-1))  #%>%
#   #filter(!instituicao %in% municipios_excluidos$instituicao  )
# 
# 
# 
# dados_grafico_variacao_municipios %>%
#   mutate(categoria= "Municípios") %>%
#   ggplot(aes(x= categoria, y= variacao_perc)) +
#   geom_quasirandom( pch = 21, fill= paleta_cores$cor_texto, color= paleta_cores$cor_fundo_painel) +
#   scale_y_log10(labels= scales::percent_format(accuracy = 1.0)) +
#   theme_vpr(paleta_cores = paleta_cores)
  
###Destacar número de municípios em 2021 e em 2025 (pode ser um inset chart)

```

```{r fig.dpi= 300}


quantidade_municipios_2021 <-NROW( finbra_2021 %>%
  filter(conta == "06 - Segurança Pública",
         coluna == "Despesas Liquidadas") )


quantidade_municipios_2025 <-NROW( finbra_2025 %>%
  filter(conta == "06 - Segurança Pública",
         coluna == "Despesas Liquidadas") )


quantidade_municipios_2021_e_2025<- NROW(finbra_2021 %>%
  filter(conta == "06 - Segurança Pública",
         coluna == "Despesas Liquidadas") %>%
  mutate(valor_2021 = valor) %>%
  select(instituicao, cod_ibge, valor_2021) %>%
  inner_join(
    finbra_2025 %>%
      filter(conta == "06 - Segurança Pública",
             coluna == "Despesas Liquidadas") %>%
      mutate(valor_2025 = valor)%>%
      select(instituicao,cod_ibge, valor_2025,populacao)
  ))


dados_grafico_variacao_municipios<-

  finbra_2021 %>%
  filter(conta == "06 - Segurança Pública",
         coluna == "Despesas Liquidadas") %>%
  mutate(valor_2021 = valor) %>%
  select(instituicao, cod_ibge, valor_2021) %>%
  inner_join(
    finbra_2025 %>%
      filter(conta == "06 - Segurança Pública",
             coluna == "Despesas Liquidadas") %>%
      mutate(valor_2025 = valor)%>%
      select(instituicao,cod_ibge, valor_2025,populacao)
  ) %>%
  mutate(valor_2021_corrigido_2025 = valor_2021 * ((num_indice_dez_2025/num_indice_dez_2021)),
         variacao_perc = ((valor_2025/valor_2021_corrigido_2025)-1)) %>%
  mutate(
    faixa_populacao = case_when(
      populacao <= 5000 ~ "Até 5 mil habitantes",
      populacao <= 10000 ~ "5.001 a 10 mil habitantes",
      populacao <= 20000 ~ "10.001 a 20 mil habitantes",
      populacao <= 50000 ~ "20.001 a 50 mil habitantes",
      populacao <= 100000 ~ "50.001 a 100 mil habitantes",
      populacao <= 500000 ~ "100.001 a 500 mil habitantes",
      populacao > 500000 ~ "Mais de 500 mil habitantes",
      TRUE ~ NA_character_
    )
  ) %>%
  mutate(faixa_populacao =  factor(faixa_populacao, levels = c("Até 5 mil habitantes", "5.001 a 10 mil habitantes","10.001 a 20 mil habitantes","20.001 a 50 mil habitantes","50.001 a 100 mil habitantes",  "100.001 a 500 mil habitantes", "Mais de 500 mil habitantes" ))) %>%
  mutate(faixa_variacao = case_when(
    variacao_perc <0 ~"<0%",
    between(variacao_perc,0,media_variacao_anos) ~ paste0("[0%,36%]" ) ,
    between(variacao_perc,media_variacao_anos,1) ~ paste0("]36%, 100%]" ) ,
    variacao_perc > 1 ~ paste0(">100%")
  )) %>%
  group_by(faixa_populacao, faixa_variacao) %>%
  summarise(quantidade = n()) %>%
  mutate(faixa_variacao =factor(faixa_variacao, levels = c("<0%","[0%,36%]","]36%, 100%]", ">100%"  )))  

dados_grafico_variacao_municipios %>%
  ggplot(aes(y= quantidade, x= faixa_variacao)) +
  geom_col(aes(fill = quantidade), show.legend = FALSE) +
  geom_text(aes(label = quantidade), vjust=1, size = 3, color = paleta_cores$cor_texto, fontface = "bold")+
  labs(
    x= "Faixas de variação",
    y= "Quantidade de municípios",
    title = "Distribuição da variação de gastos em segurança pública",
    subtitle  = "Variações entre 2021 e 2025 detalhadas por faixa de população e faixa de variação",
    caption = "Dados de 2224 municípios que registraram gastos em 2021 e 2025. Fonte STN/SICONFI. Elaboração: VPR/DIESO"
  )+
  scale_fill_continuous_sequential(palette = "Heat 2") +
  theme_vpr(paleta_cores = paleta_cores) +
  theme(
    axis.text.x = element_text(angle = 45, hjust=1, vjust=1),
    axis.text.y = element_blank()
  )+
  facet_wrap(faixa_populacao~., scales= "free_y")



```

```{r fig.dpi= 300}

participacao_seg_publica<-
  finbra_2025 %>%
  filter(conta %in% c("06 - Segurança Pública", "Despesas Exceto Intraorçamentárias", "Despesas Intraorçamentárias" ),
         coluna == "Despesas Liquidadas")%>%
  mutate(conta = ifelse(conta == "06 - Segurança Pública", "06 - Segurança Pública", "Total Despesa")) %>%
  summarise(total = sum(valor),
            populacao = mean(populacao),
            .by = c(instituicao, conta)) %>%
  pivot_wider(names_from = conta,
              values_from = total) %>%
  mutate(part_seg_pub = `06 - Segurança Pública`/`Total Despesa`,
         part_seg_pub = ifelse(is.na(part_seg_pub),0, part_seg_pub))


quantis<- quantile(participacao_seg_publica$part_seg_pub)

dados_grafico_participacao_seg_publica<-
  participacao_seg_publica %>%
  mutate(
    faixa_populacao = case_when(
      populacao <= 5000 ~ "Até 5 mil habitantes",
      populacao <= 10000 ~ "5.001 a 10 mil habitantes",
      populacao <= 20000 ~ "10.001 a 20 mil habitantes",
      populacao <= 50000 ~ "20.001 a 50 mil habitantes",
      populacao <= 100000 ~ "50.001 a 100 mil habitantes",
      populacao <= 500000 ~ "100.001 a 500 mil habitantes",
      populacao > 500000 ~ "Mais de 500 mil habitantes",
      TRUE ~ NA_character_
    )
  ) %>%
  mutate(faixa_populacao =  factor(faixa_populacao, levels = c("Até 5 mil habitantes", "5.001 a 10 mil habitantes","10.001 a 20 mil habitantes","20.001 a 50 mil habitantes","50.001 a 100 mil habitantes",  "100.001 a 500 mil habitantes", "Mais de 500 mil habitantes" ))) %>%
  mutate(faixa_participacao =case_when(
    part_seg_pub == 0 ~ "0%",
    between(part_seg_pub, 0, quantis[3]) ~"]0%, 0,025%]",
    between(part_seg_pub, quantis[3], quantis[4]) ~"]0,025%, 0,034%]",
    part_seg_pub > quantis[4] ~ ">0,034%"
    
  )) %>%
  mutate(faixa_participacao = factor(faixa_participacao, levels = c("0%","]0%, 0,025%]","]0,025%, 0,034%]",">0,034%")) ) %>%
  group_by(faixa_populacao, faixa_participacao) %>%
  summarise(quantidade = n()) 


dados_grafico_participacao_seg_publica%>%
  ggplot(aes(y= quantidade, x= faixa_participacao)) +
  geom_col(aes(fill = quantidade), show.legend = FALSE) +
  geom_text(aes(label = quantidade, 
            vjust= case_when(
              quantidade<8 & faixa_populacao == "Mais de 500 mil habitantes" ~ -1,
              quantidade>8 & faixa_populacao == "Mais de 500 mil habitantes" ~ 1,
              quantidade < 60 ~ -1,
              TRUE ~ 1
            )), 
            size = 3, 
            color = paleta_cores$cor_texto, 
            fontface = "bold")+
  labs(
    x= "Faixas de participação",
    y= "Quantidade de municípios",
    title = "Distribuição da participação de gastos em segurança pública em 2025",
    subtitle  = "Participações detalhadas por faixa de população e faixa de participação",
    caption = "Fonte STN/SICONFI. Elaboração: VPR/DIESO"
  )+
  scale_fill_continuous_sequential(palette = "Heat 2") +
  theme_vpr(paleta_cores = paleta_cores) +
  theme(
    axis.text.x = element_text(angle = 45, hjust=1, vjust=1),
    axis.text.y = element_blank()
  )+
  facet_wrap(faixa_populacao~., scales= "free_y")


```

